apiVersion: batch/v1
kind: Job
metadata:
  name: db-check
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
        - name: db-check
          image: busybox:latest
          envFrom:
            - configMapRef:
                name: db-config
          command: ["sh", "-c", "echo 'Checking db data:'; sleep 5; echo 'Done!'"]